const CarData = {
  Name: [
    "Toyota Camry SE 350",
    "Kia Soul 2016",
    "Audi A3 2019 new",
    "Ferrari 458 MM Speciale",
    "2018 Chevrolet Camaro",
    "Acura Sport Version",
    "Chevrolet Pick Truck 3.5L",
    "Toyota Tacoma 4WD",
    "Acura RDX FWD",
  ],
  brand: [
    "Toyota",
    "Kia",
    "Audi",
    "Ferrari",
    "Chevrolet",
    "Acura",
    "Chevrolet",
    "Toyota",
    "Acura",
  ],
  ImgUrl: [
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-01.jpg",
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-02.jpg",
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-03.jpg",
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-04.jpg",
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-05.jpg",
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-06.jpg",
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-07.jpg",
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-08.jpg",
    "https://dreamsrent.dreamguystech.com/html/assets/img/cars/car-09.jpg",
  ],
  Pricing: ["$400", "$80", "$45", "$160", "$36", "$30", "$77", "$30", "$80"],
  Mileage: [
    "10KM",
    "22KM",
    "10KM",
    "14KM",
    "18KM",
    "12KM",
    "10KM",
    "22KM",
    "42KM",
  ],
  Registration: [
    "2018",
    "2016",
    "2019",
    "2022",
    "2018",
    "2013",
    "2012",
    "2019",
    "2021",
  ],
  System: [
    "Auto",
    "Auto",
    "Manual",
    "Manual",
    "Manual",
    "Auto",
    "Manual",
    "Auto",
    "Auto",
  ],
  location: [
    "Germany",
    "Belgium",
    "Newyork, USA",
    "Newyork, USA",
    "Germany",
    "Newyork, USA",
    "Spain",
    "Dallas, USA",
    "Dallas, USA",
  ],
  icons_brand: ["➕", "➕", "➕", "➕", "➕", "➕"],
  type: ["Mazda", "Audi", "Honda", "Toyota", "Acura", "Tesla"],
  backgroundColor: [
    "green text-white",
    "bg-white text-black",
    "bg-white text-black",
    "bg-white text-black",
    "bg-white text-black",
    "bg-white text-black",
  ],
  Popular_Cars: {
    Name: ["Pickup", "Family MPV", "Crossover", "Sports Coupe", "Sedan"],
    Quantity: ["17", "32", "40", "10", "11", "30", "24"],
    ImgUrl: [
      "https://dreamsrent.dreamguystech.com/html/assets/img/cars/mp-vehicle-04.png",
      "https://dreamsrent.dreamguystech.com/html/assets/img/cars/mp-vehicle-05.png",
      "https://dreamsrent.dreamguystech.com/html/assets/img/cars/mp-vehicle-01.png",
      "https://dreamsrent.dreamguystech.com/html/assets/img/cars/mp-vehicle-02.png",
      "https://dreamsrent.dreamguystech.com/html/assets/img/cars/mp-vehicle-03.png",
    ],
  },
  Facts: {
    Data: ["16K+", "2547k+", "625k+", "200k+"],
    Content_Type: [
      "Happy Customers",
      "Count of Cars",
      "Car center Solutions",
      "Total Kilometers",
    ],
    Icon_Url: [
      "https://dreamsrent.dreamguystech.com/html/assets/img/icons/bx-heart.svg",
      "https://dreamsrent.dreamguystech.com/html/assets/img/icons/bx-car.svg",
      "https://dreamsrent.dreamguystech.com/html/assets/img/icons/bx-headphone.svg",
      "https://dreamsrent.dreamguystech.com/html/assets/img/icons/bx-history.svg",
    ],
  },
  Height: {
    h1: " h-16 ",
    h2: " h-16 ",
    h3: " h-16 ",
    h4: " h-16 ",
    h5: " h-16 ",
    h6: " h-16 ",
    h7: " h-16 ",
  },
  Array_FAQs: [
    "  What is about rental car deals?",
    "  In which areas do you operate?",
    "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium?",
    " Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia?",
    " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor?",
    " eque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit?",
    "  Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod?",
  ],
  PricingQuestions: {
    Card_two: {
      Get: [
        "Get Starting message",
        "Min 1 month, extend anytime",
        "Rental car prices include tax",
      ],
      Lose: [
        "Extend or return anytime",
        "Doorstep delivery in 2days",
        "Car system included free of charge",
        "Min 1 month, extend anytime",
      ],
    },
    Card_four: {
      Get: [
        "Get Starting message",
        "Min 1 month, extend anytime",
        "Rental car prices include tax",
        "Extend or return anytime",
        "Doorstep delivery in 2days",
        "Car system included free of charge",
        "Min 1 month, extend anytime",
      ],
    },
  },
  FooterContentLists: {
    List_one: [
      " ",
      "Our Company",
      "Shop Toyota",
      "Dreamsrentals USA",
      "Dreamsrentals Worldwide",
      "Dreamsrentals Racing",
      "Dreamsrentals Racing",
      "Virtual Auto Show",
    ],
    List_two: [

      "",
      "All Vehicles",
      "SUVs",
      "Trucks",
      "Cars",
      "Crossovers",
      "Electrified Vehicles",
      "Hybrids",
    ],
    List_three: [
      " ",
    "My Account",
    "Champaigns",
    "Dreamsrental Dealers",
    "Deals and Incentive",
    "Financial Services",
    "Dreamsrental Insurance",
    "Dreamsrental Care",
    ]
  },
};

export default CarData;
